---
 - name: 'vm1'
   box: 'jgabriel/rockylinux-9'
   box_name: 'ubuntu'
   box_version: "1.0"
   box_provider: 'virtualbox'
   hostname: 'rockylinux'
   dir_host: './shared_folder'
   dir_guest: '/vagrant'
   cpu: '1'
   ram: '4096'
   disk: '50GB'
   vmgui: 'false'
   host_port: '443' 
   guest_port: '443'
   file_provision: './provision/provision.sh'
...
